### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by coldwarrl** [bartosz-jarmuz/RandomFriendlyNameGenerator#2]
Hey, this is a nice and useful lib!. Could y add a license here and @nugget ?
Thanks!

**Comment by bartosz-jarmuz** [comment]
Hi, -
Sure, will do.
Its MIT license:)

pt., 21 sie 2020, 14:30 użytkownik Marco <notifications@github.com> napisał:

**Comment by bartosz-jarmuz** [comment]
I have added the license information in github.
Given it's the most permissive one and given that nuget package points to the repository, I am not going to create a new version of nuget only to introduce the license info into the package.

If I ever have new features or bugfixes, I will add & regenerate the package:)

Thanks for reporting.
